# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Architect
email: beerandncoding@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
    Infrastructure Provisioning
    Made Easy
url: https://iamtyryion.github.com/architect
github_username: iamtyrion
timezone: Asia/Kolkata
# Build settings
markdown: kramdown
remote_theme: fongandrew/hydeout
paginate: 5
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

version: 0.0.0
sidebar_home_link: true
disqus:
    shortname: architect-3
author:
    github: iamtyrion
