title: Architect
name: Architect
email: beerandncoding@gmail.com
tagline: Infrastructure Provisioning Made Easy
description: >-
    Infrastructure Provisioning
    Made Easy
url: https://iamtyrion.github.io
github_username: iamtyrion
timezone: Asia/Kolkata
# Build settings
markdown: kramdown
remote_theme: fongandrew/hydeout
paginate: 5
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

version: 0.0.0
sidebar_home_link: true
disqus:
    shortname: architect-3
author:
    name: 'Tyrion Lannister'

github_repo: https://github.com/iamtyrion/architect

twitter:
    username: vimrookie
